export const ProblemData = [
    {
        "id": "1",
        "occur_date": "2024.01.09",
        "part_number": "87210-H0500",
        "part_name": "RR Spoiler Assy",
        "model": "FB",
        "part_type": "Зарубежный",
        "problem_code": "EX001",
        "problem": "Царапина",
        "defect_qty": "18",
        "supplier": "Sambo Platec",
        "reason": "Хранение",
        "temp_cm": "Полировка",
        "temp_cm_date": "2024.01.09",
        "perm_cm": "Ремонт телеги: наклейка пэдов",
        "perm_cm_date": "2024.01.10",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Топоров Андрей",
        "system": "Экстерьер",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "2",
        "occur_date": "2024.01.09",
        "part_number": "31100-BW000",
        "part_name": "Fuel Tank Assy",
        "model": "SU2r",
        "part_type": "Локальный",
        "problem_code": "CH001",
        "problem": "Царапина",
        "defect_qty": "12",
        "supplier": "DIPO",
        "reason": "Хранение",
        "temp_cm": "Ремонт с помощью 3М ленты",
        "temp_cm_date": "2024.01.09",
        "perm_cm": "Ремонт с помощью 3М ленты",
        "perm_cm_date": "2024.01.09",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Тимченко Олег",
        "system": "Шасси",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "3",
        "occur_date": "2024.01.09",
        "part_number": "13180-12000",
        "part_name": "Nut Lock",
        "model": "HCr",
        "part_type": "Зарубежный",
        "problem_code": "CH002",
        "problem": "Ржавчина",
        "defect_qty": "200",
        "supplier": "Jinhap",
        "reason": "Хранение",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.01.11",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Кузнецов Алексей",
        "system": "Шасси",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "4",
        "occur_date": "2024.01.24",
        "part_number": "86150-H5000",
        "part_name": "Cowl Top Cover",
        "model": "HCr",
        "part_type": "Зарубежный",
        "problem_code": "EX002",
        "problem": "Деформация",
        "defect_qty": "2",
        "supplier": "Foosung",
        "reason": "Хранение",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.01.24",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Топоров Андрей",
        "system": "Экстерьер",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "5",
        "occur_date": "2024.01.29",
        "part_number": "86110-H5090",
        "part_name": "W/Shield Glass Assy",
        "model": "HCr",
        "part_type": "Зарубежный",
        "problem_code": "EX003",
        "problem": "Загрязнение ржавчиной",
        "defect_qty": "1",
        "supplier": "KAC",
        "reason": "Хранение",
        "temp_cm": "",
        "temp_cm_date": "",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ запрошены",
        "action": "Утилизация",
        "responsible": "Топоров Андрей",
        "system": "Экстерьер",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "6",
        "occur_date": "2024.01.29",
        "part_number": "86130-H5000",
        "part_name": "Door Glass Assy,RH",
        "model": "HCr",
        "part_type": "Зарубежный",
        "problem_code": "EX006",
        "problem": "Загрязнение водой",
        "defect_qty": "200",
        "supplier": "KAC",
        "reason": "Хранение",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.01.29",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Барановский Дмитрий",
        "system": "Мувинг",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "7",
        "occur_date": "2024.02.03",
        "part_number": "86110-H5090",
        "part_name": "W/Shield Glass Assy",
        "model": "HCr",
        "part_type": "Зарубежный",
        "problem_code": "EX005",
        "problem": "Загрязнение водой",
        "defect_qty": "120",
        "supplier": "KAC",
        "reason": "Хранение",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.02.03",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Топоров Андрей",
        "system": "Экстерьер",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "8",
        "occur_date": "2024.02.06",
        "part_number": "86110-H0090",
        "part_name": "W/Shield Glass Assy",
        "model": "FB",
        "part_type": "Локальный",
        "problem_code": "EX008",
        "problem": "Обогрев стекла не работает",
        "defect_qty": "49",
        "supplier": "Fuyao",
        "reason": "Поставщик",
        "temp_cm": "Сортировка",
        "temp_cm_date": "2024.02.06",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Утилизация",
        "responsible": "Топоров Андрей",
        "system": "Экстерьер",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "9",
        "occur_date": "2024.02.09",
        "part_number": "85300-BW150",
        "part_name": "Headlining Assy",
        "model": "SU2r",
        "part_type": "Локальный",
        "problem_code": "IN002",
        "problem": "Повреждение кромки",
        "defect_qty": "14",
        "supplier": "NVH Rus",
        "reason": "Поставщик",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.02.10",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Лисицын Дмитрий",
        "system": "Интерьер",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "10",
        "occur_date": "2024.02.14",
        "part_number": "89100-BW020",
        "part_name": "FOB Smart Key",
        "model": "SU2r",
        "part_type": "Зарубежный",
        "problem_code": "EL001",
        "problem": "Низкий заряд батареи",
        "defect_qty": "26",
        "supplier": "Continental",
        "reason": "Хранение",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.02.14",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Лебедев Евгений",
        "system": "Электрика",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "11",
        "occur_date": "2024.02.17",
        "part_number": "82110-H0000",
        "part_name": "I/S Door Belt Assy,LH",
        "model": "FB",
        "part_type": "Зарубежный",
        "problem_code": "MV001",
        "problem": "Уплотнительные пэды отсутствуют",
        "defect_qty": "17",
        "supplier": "DRB",
        "reason": "Поставщик",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.02.18",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Барановский Дмитрий",
        "system": "Мувинг",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "12",
        "occur_date": "2024.03.01",
        "part_number": "56110-BW000",
        "part_name": "Steering Wheel Assy",
        "model": "SU2r",
        "part_type": "Локальный",
        "problem_code": "CH006",
        "problem": "Трещина на корпусе кнопок",
        "defect_qty": "8",
        "supplier": "Samsong",
        "reason": "Поставщик",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.03.01",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Тимченко Олег",
        "system": "Шасси",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "13",
        "occur_date": "2024.03.04",
        "part_number": "85210-H0000",
        "part_name": "FR Pillar Trim Assy",
        "model": "FB",
        "part_type": "Зарубежный",
        "problem_code": "IN006",
        "problem": "Белые пятна от вибросварки",
        "defect_qty": "24",
        "supplier": "Shinki Intermobile",
        "reason": "Поставщик",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.03.05",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Лисицын Дмитрий",
        "system": "Интерьер",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    },
    {
        "id": "14",
        "occur_date": "2024.01.18",
        "part_number": "85210-H0000",
        "part_name": "FR Pillar Trim Assy",
        "model": "FB",
        "part_type": "Зарубежный",
        "problem_code": "IN003",
        "problem": "Царапины",
        "defect_qty": "31",
        "supplier": "Shinki Intermobile",
        "reason": "Поставщик",
        "temp_cm": "Ремонт",
        "temp_cm_date": "2024.01.19",
        "perm_cm": "",
        "perm_cm_date": "",
        "status": "КМ внедрены",
        "action": "Возврат на линию",
        "responsible": "Лисицын Дмитрий",
        "system": "Интерьер",
        "comment": "",
        "part_number_2": "",
        "occur_date_2": "",
        "defect_qty_2": "",
        "action_2": "",
        "comment_2": "",
        "part_number_3": "",
        "occur_date_3": "",
        "defect_qty_3": "",
        "action_3": "",
        "comment_3": "",
        "part_number_4": "",
        "occur_date_4": "",
        "defect_qty_4": "",
        "action_4": "",
        "comment_4": "",
        "part_number_5": "",
        "occur_date_5": "",
        "defect_qty_5": "",
        "action_5": "",
        "comment_5": "",
        "part_number_6": "",
        "occur_date_6": "",
        "defect_qty_6": "",
        "action_6": "",
        "comment_6": ""
    }
]